DATABASE_NAME: mcl

spring:
  application:
    name: movie-catalog-service   # Unique name of this microservice (used by Eureka registry)


  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME}   # Database connection URL (DB name = MCL)
    username: root                         # MySQL username
    password: gomo                         # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 8+ JDBC driver

  jpa:
    hibernate:
      ddl-auto: update     # Auto create/update tables based on entities (use 'validate' in production)
    show-sql: true         # Show SQL queries in console (useful for debugging)
    database-platform: org.hibernate.dialect.MySQL8Dialect   # Hibernate dialect for MySQL 8

server:
  port: 8090   # Port where this service runs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # URL of the Eureka server for registration & discovery
